robot_base_frame: base_link
transform_tolerance: 0.3

# Frequency of frontier-search-and-pursuit loop
planner_frequency: 0.33

# Failing to make a progress within this timeframe (in seconds) blacklists
# the current frontier
progress_timeout: 30.0

# We don't wanna swtich goals too often, so we wait for this amount of time
switching_timeout: 5.0

# Bias frontier selection for pursuit based on distance from robot.
# Higher the value, higher the preference for closer frontiers
potential_weight: 3.0

# Bias frontier selection for pursuit based on frontier size.
# Higher the value, higher the preference for larger frontiers
gain_weight: 1.0

# Bias frontier selection for pursuit based on num of close frontiers.
# Higher the value, higher the preference for frontiers with more close frontiers
close_frontier_weight: 1.0

# Consider a frontier worthy of pursuit only if
# number_of_points_in_frontier * map_resolution > minimum_frontier_size
minimum_frontier_size: 0.5

# If the robot is within this distance of a frontier, it is considered closed
frontier_proximity_threshold: 0.5

# Publish RViz markers to visualise frontiers
visualize: true
